module Axlsx
  # Theme represents the theme part of the package and is responsible for
  # generating the default Office theme that is required for encryption compatibility
  class Theme
    # The part name of this theme
    # @return [String]
    def pn
      THEME_PN
    end

    # Serializes the default theme to XML (complete Office theme for encryption compatibility)
    # @param [String] str
    # @return [String]
    def to_xml_string(str = '')
      str << '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      str << '<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Office Theme">'
      str << '<a:themeElements>'
      str << '<a:clrScheme name="Office">'
      str << '<a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1>'
      str << '<a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1>'
      str << '<a:dk2><a:srgbClr val="1F497D"/></a:dk2>'
      str << '<a:lt2><a:srgbClr val="EEECE1"/></a:lt2>'
      str << '<a:accent1><a:srgbClr val="4F81BD"/></a:accent1>'
      str << '<a:accent2><a:srgbClr val="C0504D"/></a:accent2>'
      str << '<a:accent3><a:srgbClr val="9BBB59"/></a:accent3>'
      str << '<a:accent4><a:srgbClr val="8064A2"/></a:accent4>'
      str << '<a:accent5><a:srgbClr val="4BACC6"/></a:accent5>'
      str << '<a:accent6><a:srgbClr val="F79646"/></a:accent6>'
      str << '<a:hlink><a:srgbClr val="0000FF"/></a:hlink>'
      str << '<a:folHlink><a:srgbClr val="800080"/></a:folHlink>'
      str << '</a:clrScheme>'
      str << '<a:fontScheme name="Office">'
      str << '<a:majorFont><a:latin typeface="Cambria"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont>'
      str << '<a:minorFont><a:latin typeface="Calibri"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont>'
      str << '</a:fontScheme>'
      str << '<a:fmtScheme name="Office">'
      str << '<a:fillStyleLst>'
      str << '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
      str << '<a:gradFill rotWithShape="1">'
      str << '<a:gsLst>'
      str << '<a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="50000"/></a:schemeClr></a:gs>'
      str << '<a:gs pos="100000"><a:schemeClr val="phClr"><a:tint val="15000"/></a:schemeClr></a:gs>'
      str << '</a:gsLst>'
      str << '<a:lin ang="16200000"/>'
      str << '</a:gradFill>'
      str << '<a:gradFill rotWithShape="1">'
      str << '<a:gsLst>'
      str << '<a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="100000"/></a:schemeClr></a:gs>'
      str << '<a:gs pos="100000"><a:schemeClr val="phClr"><a:tint val="50000"/></a:schemeClr></a:gs>'
      str << '</a:gsLst>'
      str << '<a:lin ang="16200000"/>'
      str << '</a:gradFill>'
      str << '</a:fillStyleLst>'
      str << '<a:lnStyleLst>'
      str << '<a:ln w="9525" cap="flat" cmpd="sng" algn="ctr">'
      str << '<a:solidFill><a:schemeClr val="phClr"><a:shade val="95000"/><a:satMod val="105000"/></a:schemeClr></a:solidFill>'
      str << '<a:prstDash val="solid"/>'
      str << '</a:ln>'
      str << '<a:ln w="25400" cap="flat" cmpd="sng" algn="ctr">'
      str << '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
      str << '<a:prstDash val="solid"/>'
      str << '</a:ln>'
      str << '<a:ln w="38100" cap="flat" cmpd="sng" algn="ctr">'
      str << '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
      str << '<a:prstDash val="solid"/>'
      str << '</a:ln>'
      str << '</a:lnStyleLst>'
      str << '<a:effectStyleLst>'
      str << '<a:effectStyle>'
      str << '<a:effectLst>'
      str << '<a:outerShdw blurRad="40000" dist="20000" dir="5400000" rotWithShape="false">'
      str << '<a:srgbClr val="000000"><a:alpha val="38000"/></a:srgbClr>'
      str << '</a:outerShdw>'
      str << '</a:effectLst>'
      str << '</a:effectStyle>'
      str << '<a:effectStyle>'
      str << '<a:effectLst>'
      str << '<a:outerShdw blurRad="40000" dist="23000" dir="5400000" rotWithShape="false">'
      str << '<a:srgbClr val="000000"><a:alpha val="35000"/></a:srgbClr>'
      str << '</a:outerShdw>'
      str << '</a:effectLst>'
      str << '</a:effectStyle>'
      str << '<a:effectStyle>'
      str << '<a:effectLst/>'
      str << '</a:effectStyle>'
      str << '</a:effectStyleLst>'
      str << '<a:bgFillStyleLst>'
      str << '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
      str << '<a:gradFill rotWithShape="1">'
      str << '<a:gsLst>'
      str << '<a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="40000"/></a:schemeClr></a:gs>'
      str << '<a:gs pos="100000"><a:schemeClr val="phClr"><a:shade val="20000"/></a:schemeClr></a:gs>'
      str << '</a:gsLst>'
      str << '<a:path path="circle"><a:fillToRect l="50000" t="-80000" r="50000" b="180000"/></a:path>'
      str << '</a:gradFill>'
      str << '<a:gradFill rotWithShape="1">'
      str << '<a:gsLst>'
      str << '<a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="80000"/></a:schemeClr></a:gs>'
      str << '<a:gs pos="100000"><a:schemeClr val="phClr"><a:shade val="30000"/></a:schemeClr></a:gs>'
      str << '</a:gsLst>'
      str << '<a:path path="circle"><a:fillToRect l="50000" t="50000" r="50000" b="50000"/></a:path>'
      str << '</a:gradFill>'
      str << '</a:bgFillStyleLst>'
      str << '</a:fmtScheme>'
      str << '</a:themeElements>'
      str << '<a:objectDefaults/>'
      str << '<a:extraClrSchemeLst/>'
      str << '</a:theme>'
      str
    end
  end
end
